// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:934922815800:web:18a266a05494e55451d9cd',
    messagingSenderId: '934922815800',
    projectId: 'delivrmart',
    authDomain: 'delivrmart.firebaseapp.com',
    storageBucket: 'delivrmart.firebasestorage.app',
    measurementId: 'G-543JG2HPEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:934922815800:android:1385b4d8fecddeb551d9cd',
    messagingSenderId: '934922815800',
    projectId: 'delivrmart',
    storageBucket: 'delivrmart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:934922815800:ios:2a7c8636bac9c24d51d9cd',
    messagingSenderId: '934922815800',
    projectId: 'delivrmart',
    storageBucket: 'delivrmart.firebasestorage.app',
    iosBundleId: 'com.example.delivrMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    appId: '1:934922815800:ios:2a7c8636bac9c24d51d9cd',
    messagingSenderId: '934922815800',
    projectId: 'delivrmart',
    storageBucket: 'delivrmart.firebasestorage.app',
    iosBundleId: 'com.example.delivrMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    appId: '1:934922815800:web:10aca35bafc3aac151d9cd',
    messagingSenderId: '934922815800',
    projectId: 'delivrmart',
    authDomain: 'delivrmart.firebaseapp.com',
    storageBucket: 'delivrmart.firebasestorage.app',
    measurementId: 'G-1RLQF0Y2QM',
  );
}


